spring.application.name=sancaklar
server.port=9898
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://10.242.103.14:5432/sancaklar
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
springdoc.api-docs.path=/api-docs
# Mail SMTP Ayarlar?
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fishermanauth@gmail.com
spring.mail.password=gwof kent sgsy jgee
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=true
org.jobrunr.dashboard.port=8001

