package com.sc.sancaklar.model.dto.village;

import lombok.Data;

@Data
public class VillageBuildingsModel {
    private int headquarters;
    private int headquartersCostWood;
    private int headquartersCostMeat;
    private int headquartersCostIron;
    private int barracks;
    private int barracksCostWood;
    private int barracksCostMeat;
    private int barracksCostIron;
    private int stable;
    private int stableCostWood;
    private int stableCostMeat;
    private int stableCostIron;
    private int workshop;
    private int workshopCostWood;
    private int workshopCostMeat;
    private int workshopCostIron;
    private int academy;
    private int academyCostWood;
    private int academyCostMeat;
    private int academyCostIron;
    private int smithy;
    private int smithyCostWood;
    private int smithyCostMeat;
    private int smithyCostIron;
    private int market;
    private int marketCostWood;
    private int marketCostMeat;
    private int marketCostIron;
    private int timberCamp;
    private int timberCampCostWood;
    private int timberCampCostMeat;
    private int timberCampCostIron;
    private int meatPlant;
    private int meatPlantCostWood;
    private int meatPlantCostMeat;
    private int meatPlantCostIron;
    private int ironMine;
    private int ironMineCostWood;
    private int ironMineCostMeat;
    private int ironMineCostIron;
    private int farm;
    private int farmCostWood;
    private int farmCostMeat;
    private int farmCostIron;
    private int warehouse;
    private int warehouseCostWood;
    private int warehouseCostMeat;
    private int warehouseCostIron;
    private int wall;
    private int wallCostWood;
    private int wallCostMeat;
    private int wallCostIron;

    private long headquartersDuration;
    private long barracksDuration;
    private long stableDuration;
    private long workshopDuration;
    private long academyDuration;
    private long smithyDuration;
    private long marketDuration;
    private long timberCampDuration;
    private long meatPlantDuration;
    private long ironMineDuration;
    private long farmDuration;
    private long warehouseDuration;
    private long wallDuration;
}